//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public System.Guid ID { get; set; }
        public int CenterID { get; set; }
        public string CenterName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string URL { get; set; }
        public string AuthorizeNetLogin { get; set; }
        public string AuthorizeNetTranKey { get; set; }
        public bool Deleted { get; set; }
        public byte[] CenterLogo { get; set; }
        public string CybersourceLogin { get; set; }
        public string CybersourceTranKey { get; set; }
        public string AuthorizeNetUrl { get; set; }
        public string CybersourceUrl { get; set; }
        public Nullable<System.DateTime> CreatedDateUtc { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateUtc { get; set; }
        public string MerchantID { get; set; }
        public string Token { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
