//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime CreatedDateUtc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Gender { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CenterID { get; set; }
        public Nullable<int> PrescriberDefault { get; set; }
        public Nullable<int> AddressDefault { get; set; }
        public Nullable<int> EmailDefault { get; set; }
        public Nullable<int> PhoneNumberDefault { get; set; }
        public bool IncludeClaimForm { get; set; }
        public bool MarketingOptOut { get; set; }
        public bool AutoRefill { get; set; }
        public bool AutoRenew { get; set; }
        public bool RequireOrderConfirmation { get; set; }
        public Nullable<decimal> CreditOnFile { get; set; }
        public Nullable<int> PaymentMethodDefault { get; set; }
        public string AuthorizeNetCustomerID { get; set; }
        public Nullable<int> CarrierServiceID { get; set; }
        public bool NoChildProofCaps { get; set; }
        public bool SignatureRequired { get; set; }
        public string SignatureDefault { get; set; }
        public string FullName { get; set; }
        public string SSN { get; set; }
        public string Salutation { get; set; }
        public string Interests { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ContactID { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Address Address { get; set; }
    }
}
